# -*- coding: utf-8 -*-
"""Movie Review Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dohDYys9NmqM0faJoWmitKkFFI9UE2eQ
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
import re
import string

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('stopwords')

#Step 2: Upload the dataset
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("moviereviews.csv")

#View Dataset
df.head()

df.shape

df.info()

df.describe()

#Check Missing Values
df.isnull().sum()

#Remove Duplicates
df = df.drop_duplicates()

#Sentiment Distribution
sns.countplot(x='label', data=df)

plt.title("Sentiment Distribution")

plt.show()

#Review Length
df['Review_Length'] = df['review'].fillna('').apply(len)

df.head()

plt.figure(figsize=(8,5))

plt.hist(df['Review_Length'], bins=40)

plt.title("Review Length")

plt.xlabel("Characters")

plt.ylabel("Frequency")

plt.show()

#Text Preprocessing
stemmer = PorterStemmer()

stop_words = set(stopwords.words('english'))

def clean_text(text):

    text = text.lower()

    text = re.sub(r'http\S+', '', text)

    text = re.sub(r'[^a-zA-Z]', ' ', text)

    words = text.split()

    words = [stemmer.stem(word)
             for word in words
             if word not in stop_words]

    return " ".join(words)

df['Clean_Review'] = df['review'].fillna('').apply(clean_text)
df[['review','Clean_Review']].head()

# Ensure the 'label' column is string type and clean it more robustly
# First, remove any non-alphabetic characters, then strip whitespace, and finally lowercase.
df['label'] = df['label'].astype(str).str.replace(r'[^a-zA-Z]', '', regex=True).str.strip().str.lower()

# Filter out rows where 'label' is not 'pos' or 'neg' after robust cleaning.
# This ensures that only valid labels are considered for mapping.
df = df[df['label'].isin(['pos', 'neg'])].copy() # .copy() to avoid SettingWithCopyWarning

# Now map 'pos' to 1 and 'neg' to 0.
# Since we've filtered, there should be no NaNs created by map here.
df['label'] = df['label'].map({
    'pos': 1,
    'neg': 0
})

# Convert the mapped 'label' column to integer type.
# At this point, there should be no NaNs in 'label' if the filtering was effective.
df['label'] = df['label'].astype(int)

#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df['Clean_Review'])

y = df['label']

#Train Test Split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(

X,

y,

test_size=0.20,

random_state=42
)

#Logistic Regression
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(X_train,y_train)

pred_lr = lr.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy =",accuracy_score(y_test,pred_lr))

#Naive Bayes
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

nb.fit(X_train,y_train)

pred_nb = nb.predict(X_test)

print("Accuracy =",accuracy_score(y_test,pred_nb))

#Support Vector Machine
from sklearn.svm import LinearSVC

svm = LinearSVC()

svm.fit(X_train,y_train)

pred_svm = svm.predict(X_test)

print("Accuracy =",accuracy_score(y_test,pred_svm))

#Random Forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X_train,y_train)

pred_rf = rf.predict(X_test)

print("Accuracy =",accuracy_score(y_test,pred_rf))

#Compare Accuracy
accuracy = pd.DataFrame({

'Model':['Logistic Regression','Naive Bayes','SVM','Random Forest'],

'Accuracy':[

accuracy_score(y_test,pred_lr),

accuracy_score(y_test,pred_nb),

accuracy_score(y_test,pred_svm),

accuracy_score(y_test,pred_rf)

]

})

accuracy

#Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,pred_lr)

sns.heatmap(cm,

annot=True,

fmt='d',

cmap='Blues')

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

#Classification Report
from sklearn.metrics import classification_report

print(classification_report(y_test,pred_lr))

#Predict New Review
review = ["This movie is absolutely fantastic and wonderful."]

review = clean_text(review[0])

review = tfidf.transform([review])

prediction = lr.predict(review)

if prediction[0]==1:
    print("Positive Review")
else:
    print("Negative Review")

review = ["Worst movie I have ever seen. Waste of money."]

review = clean_text(review[0])

review = tfidf.transform([review])

prediction = lr.predict(review)

if prediction[0]==1:
    print("Positive Review")
else:
    print("Negative Review")